name: 'Check Sketches Compilation Results Against Database'
description: 'Return the compilation failure of a sketch only if the database expected compilation result was Pass'
inputs:
  sketches-reports-source:
    description: 'When run from scheduled workflow, name of the workflow artifact that contains sketches reports. When run from a pull request triggered workflow, path to the folder containing sketches reports.'
    default: 'sketches-reports'
  database-reports-source:
    description: 'Provide path of database with expected compilations results.'
    default: 'database-reports'
  github-token:
    description: 'GitHub access token used to comment the memory usage comparison results to the PR thread'
    default: ${{ github.token }}
runs:
  using: 'docker'
  image: 'Dockerfile'
